name         'smarchive-googlechrome'
version      '0.1.0'
author       'Jochen Schalanda'
license      'Apache 2.0'
project_page 'https://github.com/smarchive/puppet-googlechrome'
source       'https://github.com/smarchive/puppet-googlechrome'
summary      'Puppet module for installing Google Chrome from the official repositories'
description  'This module installs Google Chrome from the official Google repository. Check README.md for details.'
